# Raw Dell Server Fans
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan1b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.8
  unit_of_measurement: RPM
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan2b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.9
  unit_of_measurement: RPM
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan3b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.10
  unit_of_measurement: RPM
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan4b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.11
  unit_of_measurement: RPM
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan5b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.12
  unit_of_measurement: RPM
- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan6b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.13
  unit_of_measurement: RPM

- platform: snmp
  host: !secret ServerIdracIP
  port: 161
  community: public
  name: RawDellServerFan7b
  baseoid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.14
  unit_of_measurement: RPM

